name: Gamja

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout site using Github Actions
        uses: actions/checkout@v3
      - name: Clone site using Github Actions
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          target: ${{ secrets.PROJECT_PATH }}
          source: ./

  Build:
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Gamja using npm
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            npm install --include=dev
            npm run build